import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  top,
  bottom,
}: Readonly<{
  top: React.ReactNode;
  bottom: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: 'flex', flexDirection: 'column' }}>
        {top}
        <div className="flex-1">{children}</div>
        {bottom}
      </body>
    </html>
  );
}
